### ISSUE TITLE
error while training on ILSVRC2015 on external hard drive

### ISSUE THREAD

**Issue by scharifa** [msracver/Flow-Guided-Feature-Aggregation#43]
I was trying to train to the ILSVRC2015 data  and since they data is large I had to put on an external hard drive and point to it. 
I have modified the .yaml file as follows:
```
dataset:
  NUM_CLASSES: 31
  dataset: ImageNetVID
# dataset_path: "./data/ILSVRC2015"
  dataset_path: "/media/stormnet/easystore/ILSVRC2015"
  image_set: DET_train_30classes+VID_train_15frames
#  root_path: "./data"
  root_path: "/media/stormnet/easystore"
  test_image_set: VID_val_videos
  proposal: rpn
  motion_iou_path: './lib/dataset/imagenet_vid_groundtruth_motion_iou.mat'
  enable_detailed_eval: true 
```
However, I am getting this error:
```
raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:07:18] src/io/local_filesys.cc:154: Check failed: allow_null  LocalFileSystem: fail to open "./output/fgfa_rfcn/imagenet_vid/resnet_v1_101_flownet_imagenet_vid_rfcn_end2end_ohem/VID_val_videos/../DET_train_30classes_VID_train_15frames/fgfa_rfcn_vid-0002.params"
```

Why is it complaining about this missing file? why is it needed anyways?

Thanks in advance.
